name: imagin
description: Professional image editor with AI capabilities

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  camera: ^0.10.5+2
  image_picker: ^1.0.4
  image: ^4.0.17
  dio: ^5.3.0
  path_provider: ^2.1.1
  gallery_saver: ^2.3.2
  permission_handler: ^10.4.0
  shutter: ^0.1.7
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  photo_view: ^0.14.0
  google_mlkit_image_labeling: ^0.10.0
  google_mlkit_object_detection: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ai_models/
    - assets/filters/